// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWcNe_3XuRsoxfEeu0NIZh8yLb3Me7P_Q',
    appId: '1:64099263206:web:02fc193ee73302c5221127',
    messagingSenderId: '64099263206',
    projectId: 'enezademo',
    authDomain: 'enezademo.firebaseapp.com',
    storageBucket: 'enezademo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlkOtU_iyzKIyfqAaGvfRtV8VGEKLMn40',
    appId: '1:64099263206:android:b77c60479daf196b221127',
    messagingSenderId: '64099263206',
    projectId: 'enezademo',
    storageBucket: 'enezademo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1wktpiocTxy_6HDB5hxJt_V7F6grr-VQ',
    appId: '1:64099263206:ios:68519d28022f4194221127',
    messagingSenderId: '64099263206',
    projectId: 'enezademo',
    storageBucket: 'enezademo.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1wktpiocTxy_6HDB5hxJt_V7F6grr-VQ',
    appId: '1:64099263206:ios:efd2c83c998915d0221127',
    messagingSenderId: '64099263206',
    projectId: 'enezademo',
    storageBucket: 'enezademo.appspot.com',
    iosBundleId: 'com.example.demo.RunnerTests',
  );
}
